tests: bug: module import fails
This patch solves the name conflict when running py.test outside venv.
Renamed package: cmd/ -> _cmd/

The error output without this fix:

Hint: make sure your test modules/packages have valid Python
names.
Traceback:
C:\Program
Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__
qbz5n2kfra8p0\lib\importlib\__init__.py:127:
in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
    tests\git\test_parser.py:6: in <module>
        import data_strings as ts
	tests\git\data_strings.py:11: in <module>
	    from cmd import CmdOutput
	    E   ImportError: cannot import name 'CmdOutput' from 'cmd'
	    (C:\Program Files\WindowsApps\PythonSoftwareFoundation.
	    Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\cmd.py)

Closes #69